Added endpoint for adding identifier
uwblueprint/glottolog3 pull request #8
Opened 2018-03-11 17:46 UTC by rogers89

2018-03-11 18:46 UTC, baieric requested changes
let's remember to add unit tests once we have validation checks. Besides that, let's just change this to RESTful design.

2018-03-11 18:46 UTC, baieric commented on glottolog3/__init__.py
> +        '/resource/identifier/add',
Let's use RESTful API design. This endpoint should be POST request to `/identifiers`. I believe you can also use `config.add_route('function_name', '/identifiers')`, which will just use function_name, which needs a `@view_config` modifier. You can search up this modifier to see how it's used in glottolog, or check out this resource: https://zaiste.net/building_a_restful_api_with_pyramid_resource_and_traversal/

2018-03-11 19:17 UTC, baieric approved these changes
LGTM!

2018-03-12 23:14 UTC, ioanacrant commented
Generally, I believe RESTful design says that the response for a POST request should be the JSON representation of the object just added and letting the status code (200) be the check that the call succeeded

2018-03-13 04:34 UTC, baieric commented on glottolog3/views.py
> +        return {'message': 'ERROR: {}'.format(e)}
Ioana uses some good conventions in #12, let's change this to just be `{ 'error': '{}'.format(e) }`

2018-03-15 23:50 UTC, rogers89 commented
Currently it just returns the name of the identifier because the SQL representation in JSON is really ugly. We can change when we add a marshmallow schema for identifiers.

2018-03-15 23:50 UTC, merged